spring.application.name=activityservice
server.port=8081

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=aiactivityfitness


eureka.client.serviceUrl.defaultZone=http://localhost:8082/eureka