spring.application.name=aiservice

server.port=8084

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=airecommendationfitness


eureka.client.serviceUrl.defaultZone=http://localhost:8082/eureka